##################################################################
# Europe
##################################################################

#################################
# Standard Moves
#################################

Write-Host "Sorting European Releases..."

Move-Item -Path ".\Europe\*Color hack*.*" -Destination ".\Europe\Hacks\Enhanced Colors"
Move-Item -Path ".\Europe\*FastROM hack*.*" -Destination ".\Europe\Hacks\FastROM"

# Pre-Release
Move-Item -Path ".\Europe\*(*Beta*)*.*" -Destination ".\Europe\Pre-Release\Beta"
Move-Item -Path ".\Europe\*(*Demo*)*.*" -Destination ".\Europe\Pre-Release\Demo"
Move-Item -Path ".\Europe\*Sampler CD*.*" -Destination ".\Europe\Pre-Release\Demo"
Move-Item -Path ".\Europe\*Sampler Disc*.*" -Destination ".\Europe\Pre-Release\Demo"
Move-Item -Path ".\Europe\*Sampler Disk*.*" -Destination ".\Europe\Pre-Release\Demo"
Move-Item -Path ".\Europe\*CD Sampler*.*" -Destination ".\Europe\Pre-Release\Demo"
Move-Item -Path ".\Europe\*Demo CD*.*" -Destination ".\Europe\Pre-Release\Demo"
Move-Item -Path ".\Europe\*Demo Disc*.*" -Destination ".\Europe\Pre-Release\Demo"
Move-Item -Path ".\Europe\*Demo Disk*.*" -Destination ".\Europe\Pre-Release\Demo"
Move-Item -Path ".\Europe\Asciiware Training CD*.*" -Destination ".\Europe\Pre-Release\Demo"
Move-Item -Path ".\Europe\*Squaresoft on PlayStation*.*" -Destination ".\Europe\Pre-Release\Demo"
Move-Item -Path ".\Europe\*PlayStation Underground*.*" -Destination ".\Europe\Pre-Release\Demo"
Move-Item -Path ".\Europe\Dreamcast Express*.*" -Destination ".\Europe\Pre-Release\Demo"
Move-Item -Path ".\Europe\Dreamcast Middleware Conference Demo Disc*.*" -Destination ".\Europe\Pre-Release\Demo"
Move-Item -Path ".\Europe\Dreamcast Promotion Disk*.*" -Destination ".\Europe\Pre-Release\Demo"
Move-Item -Path ".\Europe\Dreamon*.*" -Destination ".\Europe\Pre-Release\Demo"
Move-Item -Path ".\Europe\Generator Vol*.*" -Destination ".\Europe\Pre-Release\Demo"
Move-Item -Path ".\Europe\Interactive Multi-Game Demo Disc*.*" -Destination ".\Europe\Pre-Release\Demo"
Move-Item -Path ".\Europe\Interactive Preview Plus*.*" -Destination ".\Europe\Pre-Release\Demo"
Move-Item -Path ".\Europe\Jampack Vol*.*" -Destination ".\Europe\Pre-Release\Demo"
Move-Item -Path ".\Europe\Official Sega Dreamcast Magazine*.*" -Destination ".\Europe\Pre-Release\Demo"
Move-Item -Path ".\Europe\Official U.S. PlayStation Magazine Demo*.*" -Destination ".\Europe\Pre-Release\Demo"
Move-Item -Path ".\Europe\Pizza Hut Disc*.*" -Destination ".\Europe\Pre-Release\Demo"
Move-Item -Path ".\Europe\PlayStation Kiosk Demo*.*" -Destination ".\Europe\Pre-Release\Demo"
Move-Item -Path ".\Europe\PlayStation Picks*.*" -Destination ".\Europe\Pre-Release\Demo"
Move-Item -Path ".\Europe\PS One*.*" -Destination ".\Europe\Pre-Release\Demo"
Move-Item -Path ".\Europe\PS-X-Change*.*" -Destination ".\Europe\Pre-Release\Demo"
Move-Item -Path ".\Europe\PSone*.*" -Destination ".\Europe\Pre-Release\Demo"
Move-Item -Path ".\Europe\Toys R Us - Attack of the Killer Demos*.*" -Destination ".\Europe\Pre-Release\Demo"
Move-Item -Path ".\Europe\Toys R Us Test Drive Promotion*.*" -Destination ".\Europe\Pre-Release\Demo"
Move-Item -Path ".\Europe\*(*Proto*)*.*" -Destination ".\Europe\Pre-Release\Prototype"

# Test Cartridges & Utilities
Move-Item -Path ".\Europe\*(*Program*)*.*" -Destination ".\Europe\Test Cartridges & Utilities"
Move-Item -Path ".\Europe\*(*Enhancement*Chip*)*.*" -Destination ".\Europe\Test Cartridges & Utilities"
Move-Item -Path ".\Europe\*(*Audio*Tapes*)*.*" -Destination ".\Europe\Test Cartridges & Utilities"
Move-Item -Path ".\Europe\*(*Sample*)*.*" -Destination ".\Europe\Pre-Release\Sample"
Move-Item -Path ".\Europe\*(*Debug*)*.*" -Destination ".\Europe\Test Cartridges & Utilities"
Move-Item -Path ".\Europe\*(*Prerelease*)*.*" -Destination ".\Europe\Pre-Release"
Move-Item -Path ".\Europe\*(*Test*Program*)*.*" -Destination ".\Europe\Test Cartridges & Utilities"
Move-Item -Path ".\Europe\*Service Disc*.*" -Destination ".\Europe\Test Cartridges & Utilities"
Move-Item -Path ".\Europe\*(*SDK*Build*)*.*" -Destination ".\Europe\Test Cartridges & Utilities"
Move-Item -Path ".\Europe\*Action Replay*.*" -Destination ".\Europe\Test Cartridges & Utilities"
Move-Item -Path ".\Europe\*Super*Game*Boy*.*" -Destination ".\Europe\Test Cartridges & Utilities"
Move-Item -Path ".\Europe\*Burn-in*Test*.*" -Destination ".\Europe\Test Cartridges & Utilities"
Move-Item -Path ".\Europe\*Demonstration*Program*.*" -Destination ".\Europe\Test Cartridges & Utilities"
Move-Item -Path ".\Europe\*Diagnostics*.*" -Destination ".\Europe\Test Cartridges & Utilities"
Move-Item -Path ".\Europe\*Flash*Masta*Firmware*.*" -Destination ".\Europe\Test Cartridges & Utilities"
Move-Item -Path ".\Europe\*Game*Genie*.*" -Destination ".\Europe\Test Cartridges & Utilities"
Move-Item -Path ".\Europe\*Info Genius Productivity Pak*.*" -Destination ".\Europe\Test Cartridges & Utilities"
Move-Item -Path ".\Europe\Advanced Music Player*.*" -Destination ".\Europe\Test Cartridges & Utilities"
Move-Item -Path ".\Europe\Aging Disc DOL-*.*" -Destination ".\Europe\Test Cartridges & Utilities"
Move-Item -Path ".\Europe\Aprilia - DiTech Interface*.*" -Destination ".\Europe\Test Cartridges & Utilities"
Move-Item -Path ".\Europe\Atari*PAM*.*" -Destination ".\Europe\Test Cartridges & Utilities"
Move-Item -Path ".\Europe\Breaker Pro*.*" -Destination ".\Europe\Test Cartridges & Utilities"
Move-Item -Path ".\Europe\Cheats 'N Codes Volume*.*" -Destination ".\Europe\Test Cartridges & Utilities"
Move-Item -Path ".\Europe\Code Breaker*.*" -Destination ".\Europe\Test Cartridges & Utilities"
Move-Item -Path ".\Europe\CodeBreaker*.*" -Destination ".\Europe\Test Cartridges & Utilities"
Move-Item -Path ".\Europe\Codemasters Demo CD*.*" -Destination ".\Europe\Test Cartridges & Utilities"
Move-Item -Path ".\Europe\Doctor GB Card*.*" -Destination ".\Europe\Test Cartridges & Utilities"
Move-Item -Path ".\Europe\Dreamkey*.*" -Destination ".\Europe\Test Cartridges & Utilities"
Move-Item -Path ".\Europe\Game Boy Camera*.*" -Destination ".\Europe\Test Cartridges & Utilities"
Move-Item -Path ".\Europe\Game Boy Player Start-Up Disc*.*" -Destination ".\Europe\Test Cartridges & Utilities"
Move-Item -Path ".\Europe\GameBooster 64*.*" -Destination ".\Europe\Test Cartridges & Utilities"
Move-Item -Path ".\Europe\GameShark*.*" -Destination ".\Europe\Test Cartridges & Utilities"
Move-Item -Path ".\Europe\GBA Jukebox*.*" -Destination ".\Europe\Test Cartridges & Utilities"
Move-Item -Path ".\Europe\GBA Personal Organizer*.*" -Destination ".\Europe\Test Cartridges & Utilities"
Move-Item -Path ".\Europe\JRA PAT for Dreamcast*.*" -Destination ".\Europe\Test Cartridges & Utilities"
Move-Item -Path ".\Europe\Lynx II Production Test Program (USA)*.*" -Destination ".\Europe\Test Cartridges & Utilities"
Move-Item -Path ".\Europe\Nintendo 64 Modem*.*" -Destination ".\Europe\Test Cartridges & Utilities"
Move-Item -Path ".\Europe\Randnet*.*" -Destination ".\Europe\Test Cartridges & Utilities"
Move-Item -Path ".\Europe\Ultimate Codes for Use with*.*" -Destination ".\Europe\Test Cartridges & Utilities"
Move-Item -Path ".\Europe\Web Browser*.*" -Destination ".\Europe\Test Cartridges & Utilities"
Move-Item -Path ".\Europe\XBAND*.*" -Destination ".\Europe\Test Cartridges & Utilities"
Move-Item -Path ".\Europe\Game Boy Aging Cartridge*.*" -Destination ".\Europe\Test Cartridges & Utilities"
Move-Item -Path ".\Europe\Atari 7800 Development Card (USA).*" -Destination ".\Europe\Test Cartridges & Utilities"
Move-Item -Path ".\Europe\Super NES Control Deck Tester (USA)*.*" -Destination ".\Europe\Test Cartridges & Utilities"
Move-Item -Path ".\Europe\World Class Service Super Nintendo Tester (USA).*" -Destination ".\Europe\Test Cartridges & Utilities"

# Alternate Releases
Move-Item -Path ".\Europe\*(*Promo*)*.*" -Destination ".\Europe\Alternate Releases"
Move-Item -Path ".\Europe\*(*Arcade*)*.*" -Destination ".\Europe\Alternate Releases"
Move-Item -Path ".\Europe\*(*Anthology*)*.*" -Destination ".\Europe\Alternate Releases\Collections"
Move-Item -Path ".\Europe\*(*Capcom*Classics*Mini*Mix*)*.*" -Destination ".\Europe\Alternate Releases\Collections"
Move-Item -Path ".\Europe\*(*Collect*)*.*" -Destination ".\Europe\Alternate Releases\Collections"
Move-Item -Path ".\Europe\*(*Disney*)*.*" -Destination ".\Europe\Alternate Releases"
Move-Item -Path ".\Europe\*(*e-Reader*)*.*" -Destination ".\Europe\Alternate Releases\eReader Edition"
Move-Item -Path ".\Europe\*(*Final*Cut*)*.*" -Destination ".\Europe\Alternate Releases"
Move-Item -Path ".\Europe\*(*GameCube*)*.*" -Destination ".\Europe\Alternate Releases\GameCube Edition"
Move-Item -Path ".\Europe\*(*Genesis*Mini*)*.*" -Destination ".\Europe\Alternate Releases"
Move-Item -Path ".\Europe\*(*LodgeNet*)*.*" -Destination ".\Europe\Alternate Releases"
Move-Item -Path ".\Europe\*(*Namco*Museum*)*.*" -Destination ".\Europe\Alternate Releases\Collections"
Move-Item -Path ".\Europe\*(*PC*Rerelease*)*.*" -Destination ".\Europe\Alternate Releases"
Move-Item -Path ".\Europe\*(*Sega*)*.*" -Destination ".\Europe\Alternate Releases"
Move-Item -Path ".\Europe\*(*Switch*)*.*" -Destination ".\Europe\Alternate Releases\Switch Online"
Move-Item -Path ".\Europe\*(*Virtual*Console)*.*" -Destination ".\Europe\Alternate Releases\Virtual Console"
Move-Item -Path ".\Europe\*(*Retro-Bit*)*.*" -Destination ".\Europe\Alternate Releases\"
Move-Item -Path ".\Europe\*(*iam8bit*)*.*" -Destination ".\Europe\Alternate Releases\"
Move-Item -Path ".\Europe\*(*Capcom*Town*)*.*" -Destination ".\Europe\Alternate Releases\"
Move-Item -Path ".\Europe\*(*Limited Run Games*)*.*" -Destination ".\Europe\Alternate Releases\"
Move-Item -Path ".\Europe\*(*Steam*)*.*" -Destination ".\Europe\Alternate Releases\"
Move-Item -Path ".\Europe\*(*QUByte Classics*)*.*" -Destination ".\Europe\Alternate Releases\"
Move-Item -Path ".\Europe\*(*Piko Interactive*)*.*" -Destination ".\Europe\Alternate Releases\"
Move-Item -Path ".\Europe\*(Strictly Limited Games)*.*" -Destination ".\Europe\Alternate Releases\"
Move-Item -Path ".\Europe\*(Evercade)*.*" -Destination ".\Europe\Alternate Releases\"
Move-Item -Path ".\Europe\*(*Wii*)*.*" -Destination ".\Europe\Alternate Releases"
Move-Item -Path ".\Europe\e-Reader (USA)*.*" -Destination ".\Europe\Alternate Releases\eReader Edition"
Move-Item -Path ".\Europe\*(Alt)*.*" -Destination ".\Europe\Alternate Releases\"
Move-Item -Path ".\Europe\*(*Alternate*)*.*" -Destination ".\Europe\Alternate Releases\"
Move-Item -Path ".\Europe\*(PROPER 12K)*.*" -Destination ".\Europe\Alternate Releases\"

# Alternate Releases - Multi-Cart
Move-Item -Path ".\Europe\2 Game Pack*.*" -Destination ".\Europe\Alternate Releases\Multi-Cart"
Move-Item -Path ".\Europe\2 Games in 1*.*" -Destination ".\Europe\Alternate Releases\Multi-Cart"
Move-Item -Path ".\Europe\2 Games in One*.*" -Destination ".\Europe\Alternate Releases\Multi-Cart"
Move-Item -Path ".\Europe\2 Great Games*.*" -Destination ".\Europe\Alternate Releases\Multi-Cart"
Move-Item -Path ".\Europe\2 in 1 Game Pack*.*" -Destination ".\Europe\Alternate Releases\Multi-Cart"
Move-Item -Path ".\Europe\2-in-1 Fun Pack*.*" -Destination ".\Europe\Alternate Releases\Multi-Cart"
Move-Item -Path ".\Europe\3 Game Pack*.*" -Destination ".\Europe\Alternate Releases\Multi-Cart"
Move-Item -Path ".\Europe\3 Games in 1*.*" -Destination ".\Europe\Alternate Releases\Multi-Cart"
Move-Item -Path ".\Europe\3 Games in One*.*" -Destination ".\Europe\Alternate Releases\Multi-Cart"
Move-Item -Path ".\Europe\4 Games on One Game Pak*.*" -Destination ".\Europe\Alternate Releases\Multi-Cart"
Move-Item -Path ".\Europe\4 in 1 + 8 in 1*.*" -Destination ".\Europe\Alternate Releases\Multi-Cart"

# Alternate Releases - Manual Assignment
Move-Item -Path ".\Europe\Blitz! - Action Football (USA, Europe) (0F11CE0C).*" -Destination ".\Europe\Alternate Releases\"
Move-Item -Path ".\Europe\Blitz! - Action Football (USA, Europe) (881B27C5).*" -Destination ".\Europe\Alternate Releases\"
Move-Item -Path ".\Europe\Pole Position (USA) (A00ED3D6).*" -Destination ".\Europe\Alternate Releases\"
Move-Item -Path ".\Europe\Pole Position (USA) (C10F37D8).*" -Destination ".\Europe\Alternate Releases\"
Move-Item -Path ".\Europe\*[*Un-Worked Design by Supper*]*.*" -Destination ".\Europe\Alternate Releases\"
Move-Item -Path ".\Europe\Tecmo NBA Basketball (USA) (NES-N7).*" -Destination ".\Europe\Alternate Releases\"
Move-Item -Path ".\Europe\Tecmo Super NBA Basketball (USA) (SNS-NA).*" -Destination ".\Europe\Alternate Releases\"
Move-Item -Path ".\Europe\Wild Gunman (Japan, USA) (En).*" -Destination ".\Europe\Alternate Releases\"
Move-Item -Path ".\Europe\Kirby's Adventure (Canada) (Fr).*" -Destination ".\Europe\Alternate Releases\"
Move-Item -Path ".\Europe\Legend of Zelda, The - A Link to the Past (Canada) (Fr).*" -Destination ".\Europe\Alternate Releases\"
Move-Item -Path ".\Europe\Alex Kidd in Miracle World (USA, Europe, Brazil) (En) (Rev 1).*" -Destination ".\Europe\Alternate Releases\"
Move-Item -Path ".\Europe\Altered Beast (Japan, USA) (En) (Rev A).*" -Destination ".\Europe\Alternate Releases\"
Move-Item -Path ".\Europe\Arcade Legends Sega Mega Drive (World).*" -Destination ".\Europe\Alternate Releases\"
Move-Item -Path ".\Europe\Arcade Legends Sega Mega Drive ~ Arcade Legends Sega Genesis ~ Mega Drive Play TV (World).*" -Destination ".\Europe\Alternate Releases\"
Move-Item -Path ".\Europe\Arcade Legends Street Fighter II' - Special Champion Edition (World).*" -Destination ".\Europe\Alternate Releases\"
Move-Item -Path ".\Europe\Arcade Legends Street Fighter II' - Special Champion Edition ~ Mega Drive Play TV 3 (World).*" -Destination ".\Europe\Alternate Releases\"
Move-Item -Path ".\Europe\FZ Senki Axis ~ Final Zone (Japan, USA) (En).*" -Destination ".\Europe\Alternate Releases\"
Move-Item -Path ".\Europe\Legend of Galahad, The ~ Galahad (USA, Europe).*" -Destination ".\Europe\Alternate Releases\"
Move-Item -Path ".\Europe\Michael Jackson's Moonwalker (Japan, USA) (En).*" -Destination ".\Europe\Alternate Releases\"
Move-Item -Path ".\Europe\NHL '94 (USA, Europe) (Re-release).*" -Destination ".\Europe\Alternate Releases\"
Move-Item -Path ".\Europe\NHLPA Hockey 93 (USA, Europe) (EA Sports).*" -Destination ".\Europe\Alternate Releases\"
Move-Item -Path ".\Europe\PGA Tour Golf (USA) (HeartBeat Catalyst).*" -Destination ".\Europe\Alternate Releases\"
Move-Item -Path ".\Europe\Raiden Densetsu ~ Raiden Trad (Japan, USA) (En).*" -Destination ".\Europe\Alternate Releases\"
Move-Item -Path ".\Europe\Senjou no Ookami II ~ Mercs (World).*" -Destination ".\Europe\Alternate Releases\"
Move-Item -Path ".\Europe\Sonic Compilation ~ Sonic Classics (USA, Europe, Korea) (En) (Rev A).*" -Destination ".\Europe\Alternate Releases\"
Move-Item -Path ".\Europe\Tatsujin ~ Truxton (World).*" -Destination ".\Europe\Alternate Releases\"
Move-Item -Path ".\Europe\World Cup Soccer ~ World Championship Soccer (Japan, USA) (En) (Rev B).*" -Destination ".\Europe\Alternate Releases\"

# Previous Revisions - Manual Assignment
Move-Item -Path ".\Europe\Lost Vikings, The (USA) (November, 1993).*" -Destination ".\Europe\Previous Revisions"
Move-Item -Path ".\Europe\Olympic Gold (Japan, USA) (En,Fr,De,Es,It,Nl,Pt,Sv).*" -Destination ".\Europe\Previous Revisions"
Move-Item -Path ".\Europe\PGA Tour Golf (USA, Europe) (PGA07).*" -Destination ".\Europe\Previous Revisions"
Move-Item -Path ".\Europe\Revenge of Shinobi, The (Japan, USA) (En).*" -Destination ".\Europe\Previous Revisions"
Move-Item -Path ".\Europe\Super Monaco GP (Japan, USA) (En,Ja).*" -Destination ".\Europe\Previous Revisions"
Move-Item -Path ".\Europe\Super Monaco GP (USA) (En,Ja).*" -Destination ".\Europe\Previous Revisions"
Move-Item -Path ".\Europe\Tinhead (USA) (Ballistic) (April, 1994).*" -Destination ".\Europe\Previous Revisions"

# Hacked Releases
Move-Item -Path ".\Europe\*(*Hack*)*.*" -Destination ".\Europe\Hacks"

# Aftermarket Releases
Move-Item -Path ".\Europe\*(*Aftermarket*)*.*" -Destination ".\Europe\Aftermarket Releases"
Move-Item -Path ".\Europe\*(*Pirate*)*.*" -Destination ".\Europe\Aftermarket Releases"

# Aftermarket Releases - Manual Assignment
Move-Item -Path ".\Europe\River City Girls Zero*.*" -Destination ".\Europe\Aftermarket Releases"
Move-Item -Path ".\Europe\8-BIT ADV STEINS;GATE*.*" -Destination ".\Europe\Aftermarket Releases"

# Unlicensed Releases
Move-Item -Path ".\Europe\*(*Unl*)*.*" -Destination ".\Europe\Unlicensed Releases"

# Official Releases
Move-Item -Path ".\Europe\*.*" -Destination ".\Europe\Official Releases"

Write-Host "Sorting for Europe Complete."