##################################################################
# Japan
##################################################################

#################################
# Standard Moves
#################################

Write-Host "Sorting Japanese Releases..."

#################################
# Standard Moves
#################################

Write-Host "Sorting Japanese Releases..."

Move-Item -Path ".\Japan\*Color hack*.*" -Destination ".\Japan\Hacks\Enhanced Colors"
Move-Item -Path ".\Japan\*FastROM hack*.*" -Destination ".\Japan\Hacks\FastROM"

# Pre-Release
Move-Item -Path ".\Japan\*(*Beta*)*.*" -Destination ".\Japan\Pre-Release\Beta"
Move-Item -Path ".\Japan\*(*Demo*)*.*" -Destination ".\Japan\Pre-Release\Demo"
Move-Item -Path ".\Japan\*Sampler CD*.*" -Destination ".\Japan\Pre-Release\Demo"
Move-Item -Path ".\Japan\*Sampler Disc*.*" -Destination ".\Japan\Pre-Release\Demo"
Move-Item -Path ".\Japan\*Sampler Disk*.*" -Destination ".\Japan\Pre-Release\Demo"
Move-Item -Path ".\Japan\*CD Sampler*.*" -Destination ".\Japan\Pre-Release\Demo"
Move-Item -Path ".\Japan\*Demo CD*.*" -Destination ".\Japan\Pre-Release\Demo"
Move-Item -Path ".\Japan\*Demo Disc*.*" -Destination ".\Japan\Pre-Release\Demo"
Move-Item -Path ".\Japan\*Demo Disk*.*" -Destination ".\Japan\Pre-Release\Demo"
Move-Item -Path ".\Japan\Asciiware Training CD*.*" -Destination ".\Japan\Pre-Release\Demo"
Move-Item -Path ".\Japan\*Squaresoft on PlayStation*.*" -Destination ".\Japan\Pre-Release\Demo"
Move-Item -Path ".\Japan\*PlayStation Underground*.*" -Destination ".\Japan\Pre-Release\Demo"
Move-Item -Path ".\Japan\Dreamcast Express*.*" -Destination ".\Japan\Pre-Release\Demo"
Move-Item -Path ".\Japan\Dreamcast Middleware Conference Demo Disc*.*" -Destination ".\Japan\Pre-Release\Demo"
Move-Item -Path ".\Japan\Dreamcast Promotion Disk*.*" -Destination ".\Japan\Pre-Release\Demo"
Move-Item -Path ".\Japan\Dreamon*.*" -Destination ".\Japan\Pre-Release\Demo"
Move-Item -Path ".\Japan\Generator Vol*.*" -Destination ".\Japan\Pre-Release\Demo"
Move-Item -Path ".\Japan\Interactive Multi-Game Demo Disc*.*" -Destination ".\Japan\Pre-Release\Demo"
Move-Item -Path ".\Japan\Interactive Preview Plus*.*" -Destination ".\Japan\Pre-Release\Demo"
Move-Item -Path ".\Japan\Jampack Vol*.*" -Destination ".\Japan\Pre-Release\Demo"
Move-Item -Path ".\Japan\Official Sega Dreamcast Magazine*.*" -Destination ".\Japan\Pre-Release\Demo"
Move-Item -Path ".\Japan\Official U.S. PlayStation Magazine Demo*.*" -Destination ".\Japan\Pre-Release\Demo"
Move-Item -Path ".\Japan\Pizza Hut Disc*.*" -Destination ".\Japan\Pre-Release\Demo"
Move-Item -Path ".\Japan\PlayStation Kiosk Demo*.*" -Destination ".\Japan\Pre-Release\Demo"
Move-Item -Path ".\Japan\PlayStation Picks*.*" -Destination ".\Japan\Pre-Release\Demo"
Move-Item -Path ".\Japan\PS One*.*" -Destination ".\Japan\Pre-Release\Demo"
Move-Item -Path ".\Japan\PS-X-Change*.*" -Destination ".\Japan\Pre-Release\Demo"
Move-Item -Path ".\Japan\PSone*.*" -Destination ".\Japan\Pre-Release\Demo"
Move-Item -Path ".\Japan\Toys R Us - Attack of the Killer Demos*.*" -Destination ".\Japan\Pre-Release\Demo"
Move-Item -Path ".\Japan\Toys R Us Test Drive Promotion*.*" -Destination ".\Japan\Pre-Release\Demo"
Move-Item -Path ".\Japan\*(*Proto*)*.*" -Destination ".\Japan\Pre-Release\Prototype"

# Test Cartridges & Utilities
Move-Item -Path ".\Japan\*(*Program*)*.*" -Destination ".\Japan\Test Cartridges & Utilities"
Move-Item -Path ".\Japan\*(*Enhancement*Chip*)*.*" -Destination ".\Japan\Test Cartridges & Utilities"
Move-Item -Path ".\Japan\*(*Audio*Tapes*)*.*" -Destination ".\Japan\Test Cartridges & Utilities"
Move-Item -Path ".\Japan\*(*Sample*)*.*" -Destination ".\Japan\Pre-Release\Sample"
Move-Item -Path ".\Japan\*(*Debug*)*.*" -Destination ".\Japan\Test Cartridges & Utilities"
Move-Item -Path ".\Japan\*(*Prerelease*)*.*" -Destination ".\Japan\Pre-Release"
Move-Item -Path ".\Japan\*(*Test*Program*)*.*" -Destination ".\Japan\Test Cartridges & Utilities"
Move-Item -Path ".\Japan\*Service Disc*.*" -Destination ".\Japan\Test Cartridges & Utilities"
Move-Item -Path ".\Japan\*(*SDK*Build*)*.*" -Destination ".\Japan\Test Cartridges & Utilities"
Move-Item -Path ".\Japan\*Action Replay*.*" -Destination ".\Japan\Test Cartridges & Utilities"
Move-Item -Path ".\Japan\*Super*Game*Boy*.*" -Destination ".\Japan\Test Cartridges & Utilities"
Move-Item -Path ".\Japan\*Burn-in*Test*.*" -Destination ".\Japan\Test Cartridges & Utilities"
Move-Item -Path ".\Japan\*Demonstration*Program*.*" -Destination ".\Japan\Test Cartridges & Utilities"
Move-Item -Path ".\Japan\*Diagnostics*.*" -Destination ".\Japan\Test Cartridges & Utilities"
Move-Item -Path ".\Japan\*Flash*Masta*Firmware*.*" -Destination ".\Japan\Test Cartridges & Utilities"
Move-Item -Path ".\Japan\*Game*Genie*.*" -Destination ".\Japan\Test Cartridges & Utilities"
Move-Item -Path ".\Japan\*Info Genius Productivity Pak*.*" -Destination ".\Japan\Test Cartridges & Utilities"
Move-Item -Path ".\Japan\Advanced Music Player*.*" -Destination ".\Japan\Test Cartridges & Utilities"
Move-Item -Path ".\Japan\Aging Disc DOL-*.*" -Destination ".\Japan\Test Cartridges & Utilities"
Move-Item -Path ".\Japan\Aprilia - DiTech Interface*.*" -Destination ".\Japan\Test Cartridges & Utilities"
Move-Item -Path ".\Japan\Atari*PAM*.*" -Destination ".\Japan\Test Cartridges & Utilities"
Move-Item -Path ".\Japan\Breaker Pro*.*" -Destination ".\Japan\Test Cartridges & Utilities"
Move-Item -Path ".\Japan\Cheats 'N Codes Volume*.*" -Destination ".\Japan\Test Cartridges & Utilities"
Move-Item -Path ".\Japan\Code Breaker*.*" -Destination ".\Japan\Test Cartridges & Utilities"
Move-Item -Path ".\Japan\CodeBreaker*.*" -Destination ".\Japan\Test Cartridges & Utilities"
Move-Item -Path ".\Japan\Codemasters Demo CD*.*" -Destination ".\Japan\Test Cartridges & Utilities"
Move-Item -Path ".\Japan\Doctor GB Card*.*" -Destination ".\Japan\Test Cartridges & Utilities"
Move-Item -Path ".\Japan\Dreamkey*.*" -Destination ".\Japan\Test Cartridges & Utilities"
Move-Item -Path ".\Japan\Game Boy Camera*.*" -Destination ".\Japan\Test Cartridges & Utilities"
Move-Item -Path ".\Japan\Game Boy Player Start-Up Disc*.*" -Destination ".\Japan\Test Cartridges & Utilities"
Move-Item -Path ".\Japan\GameBooster 64*.*" -Destination ".\Japan\Test Cartridges & Utilities"
Move-Item -Path ".\Japan\GameShark*.*" -Destination ".\Japan\Test Cartridges & Utilities"
Move-Item -Path ".\Japan\GBA Jukebox*.*" -Destination ".\Japan\Test Cartridges & Utilities"
Move-Item -Path ".\Japan\GBA Personal Organizer*.*" -Destination ".\Japan\Test Cartridges & Utilities"
Move-Item -Path ".\Japan\JRA PAT for Dreamcast*.*" -Destination ".\Japan\Test Cartridges & Utilities"
Move-Item -Path ".\Japan\Lynx II Production Test Program (USA)*.*" -Destination ".\Japan\Test Cartridges & Utilities"
Move-Item -Path ".\Japan\Nintendo 64 Modem*.*" -Destination ".\Japan\Test Cartridges & Utilities"
Move-Item -Path ".\Japan\Randnet*.*" -Destination ".\Japan\Test Cartridges & Utilities"
Move-Item -Path ".\Japan\Ultimate Codes for Use with*.*" -Destination ".\Japan\Test Cartridges & Utilities"
Move-Item -Path ".\Japan\Web Browser*.*" -Destination ".\Japan\Test Cartridges & Utilities"
Move-Item -Path ".\Japan\XBAND*.*" -Destination ".\Japan\Test Cartridges & Utilities"
Move-Item -Path ".\Japan\Game Boy Aging Cartridge*.*" -Destination ".\Japan\Test Cartridges & Utilities"
Move-Item -Path ".\Japan\Atari 7800 Development Card (USA).*" -Destination ".\Japan\Test Cartridges & Utilities"
Move-Item -Path ".\Japan\Super NES Control Deck Tester (USA)*.*" -Destination ".\Japan\Test Cartridges & Utilities"
Move-Item -Path ".\Japan\World Class Service Super Nintendo Tester (USA).*" -Destination ".\Japan\Test Cartridges & Utilities"

# Alternate Releases
Move-Item -Path ".\Japan\*(*Promo*)*.*" -Destination ".\Japan\Alternate Releases"
Move-Item -Path ".\Japan\*(*Arcade*)*.*" -Destination ".\Japan\Alternate Releases"
Move-Item -Path ".\Japan\*(*Anthology*)*.*" -Destination ".\Japan\Alternate Releases\Collections"
Move-Item -Path ".\Japan\*(*Capcom*Classics*Mini*Mix*)*.*" -Destination ".\Japan\Alternate Releases\Collections"
Move-Item -Path ".\Japan\*(*Collect*)*.*" -Destination ".\Japan\Alternate Releases\Collections"
Move-Item -Path ".\Japan\*(*Disney*)*.*" -Destination ".\Japan\Alternate Releases"
Move-Item -Path ".\Japan\*(*e-Reader*)*.*" -Destination ".\Japan\Alternate Releases\eReader Edition"
Move-Item -Path ".\Japan\*(*Final*Cut*)*.*" -Destination ".\Japan\Alternate Releases"
Move-Item -Path ".\Japan\*(*GameCube*)*.*" -Destination ".\Japan\Alternate Releases\GameCube Edition"
Move-Item -Path ".\Japan\*(*Genesis*Mini*)*.*" -Destination ".\Japan\Alternate Releases"
Move-Item -Path ".\Japan\*(*LodgeNet*)*.*" -Destination ".\Japan\Alternate Releases"
Move-Item -Path ".\Japan\*(*Namco*Museum*)*.*" -Destination ".\Japan\Alternate Releases\Collections"
Move-Item -Path ".\Japan\*(*PC*Rerelease*)*.*" -Destination ".\Japan\Alternate Releases"
Move-Item -Path ".\Japan\*(*Sega*)*.*" -Destination ".\Japan\Alternate Releases"
Move-Item -Path ".\Japan\*(*Switch*)*.*" -Destination ".\Japan\Alternate Releases\Switch Online"
Move-Item -Path ".\Japan\*(*Virtual*Console)*.*" -Destination ".\Japan\Alternate Releases\Virtual Console"
Move-Item -Path ".\Japan\*(*Retro-Bit*)*.*" -Destination ".\Japan\Alternate Releases\"
Move-Item -Path ".\Japan\*(*iam8bit*)*.*" -Destination ".\Japan\Alternate Releases\"
Move-Item -Path ".\Japan\*(*Capcom*Town*)*.*" -Destination ".\Japan\Alternate Releases\"
Move-Item -Path ".\Japan\*(*Limited Run Games*)*.*" -Destination ".\Japan\Alternate Releases\"
Move-Item -Path ".\Japan\*(*Steam*)*.*" -Destination ".\Japan\Alternate Releases\"
Move-Item -Path ".\Japan\*(*QUByte Classics*)*.*" -Destination ".\Japan\Alternate Releases\"
Move-Item -Path ".\Japan\*(*Piko Interactive*)*.*" -Destination ".\Japan\Alternate Releases\"
Move-Item -Path ".\Japan\*(Strictly Limited Games)*.*" -Destination ".\Japan\Alternate Releases\"
Move-Item -Path ".\Japan\*(Evercade)*.*" -Destination ".\Japan\Alternate Releases\"
Move-Item -Path ".\Japan\*(*Wii*)*.*" -Destination ".\Japan\Alternate Releases"
Move-Item -Path ".\Japan\e-Reader (USA)*.*" -Destination ".\Japan\Alternate Releases\eReader Edition"
Move-Item -Path ".\Japan\*(Alt)*.*" -Destination ".\Japan\Alternate Releases\"
Move-Item -Path ".\Japan\*(*Alternate*)*.*" -Destination ".\Japan\Alternate Releases\"
Move-Item -Path ".\Japan\*(PROPER 12K)*.*" -Destination ".\Japan\Alternate Releases\"

# Alternate Releases - Multi-Cart
Move-Item -Path ".\Japan\2 Game Pack*.*" -Destination ".\Japan\Alternate Releases\Multi-Cart"
Move-Item -Path ".\Japan\2 Games in 1*.*" -Destination ".\Japan\Alternate Releases\Multi-Cart"
Move-Item -Path ".\Japan\2 Games in One*.*" -Destination ".\Japan\Alternate Releases\Multi-Cart"
Move-Item -Path ".\Japan\2 Great Games*.*" -Destination ".\Japan\Alternate Releases\Multi-Cart"
Move-Item -Path ".\Japan\2 in 1 Game Pack*.*" -Destination ".\Japan\Alternate Releases\Multi-Cart"
Move-Item -Path ".\Japan\2-in-1 Fun Pack*.*" -Destination ".\Japan\Alternate Releases\Multi-Cart"
Move-Item -Path ".\Japan\3 Game Pack*.*" -Destination ".\Japan\Alternate Releases\Multi-Cart"
Move-Item -Path ".\Japan\3 Games in 1*.*" -Destination ".\Japan\Alternate Releases\Multi-Cart"
Move-Item -Path ".\Japan\3 Games in One*.*" -Destination ".\Japan\Alternate Releases\Multi-Cart"
Move-Item -Path ".\Japan\4 Games on One Game Pak*.*" -Destination ".\Japan\Alternate Releases\Multi-Cart"
Move-Item -Path ".\Japan\4 in 1 + 8 in 1*.*" -Destination ".\Japan\Alternate Releases\Multi-Cart"

# Alternate Releases - Manual Assignment
Move-Item -Path ".\Japan\Blitz! - Action Football (USA, Europe) (0F11CE0C).*" -Destination ".\Japan\Alternate Releases\"
Move-Item -Path ".\Japan\Blitz! - Action Football (USA, Europe) (881B27C5).*" -Destination ".\Japan\Alternate Releases\"
Move-Item -Path ".\Japan\Pole Position (USA) (A00ED3D6).*" -Destination ".\Japan\Alternate Releases\"
Move-Item -Path ".\Japan\Pole Position (USA) (C10F37D8).*" -Destination ".\Japan\Alternate Releases\"
Move-Item -Path ".\Japan\*[*Un-Worked Design by Supper*]*.*" -Destination ".\Japan\Alternate Releases\"
Move-Item -Path ".\Japan\Tecmo NBA Basketball (USA) (NES-N7).*" -Destination ".\Japan\Alternate Releases\"
Move-Item -Path ".\Japan\Tecmo Super NBA Basketball (USA) (SNS-NA).*" -Destination ".\Japan\Alternate Releases\"
Move-Item -Path ".\Japan\Wild Gunman (Japan, USA) (En).*" -Destination ".\Japan\Alternate Releases\"
Move-Item -Path ".\Japan\Kirby's Adventure (Canada) (Fr).*" -Destination ".\Japan\Alternate Releases\"
Move-Item -Path ".\Japan\Legend of Zelda, The - A Link to the Past (Canada) (Fr).*" -Destination ".\Japan\Alternate Releases\"
Move-Item -Path ".\Japan\Alex Kidd in Miracle World (USA, Europe, Brazil) (En) (Rev 1).*" -Destination ".\Japan\Alternate Releases\"
Move-Item -Path ".\Japan\Altered Beast (Japan, USA) (En) (Rev A).*" -Destination ".\Japan\Alternate Releases\"
Move-Item -Path ".\Japan\Arcade Legends Sega Mega Drive (World).*" -Destination ".\Japan\Alternate Releases\"
Move-Item -Path ".\Japan\Arcade Legends Sega Mega Drive ~ Arcade Legends Sega Genesis ~ Mega Drive Play TV (World).*" -Destination ".\Japan\Alternate Releases\"
Move-Item -Path ".\Japan\Arcade Legends Street Fighter II' - Special Champion Edition (World).*" -Destination ".\Japan\Alternate Releases\"
Move-Item -Path ".\Japan\Arcade Legends Street Fighter II' - Special Champion Edition ~ Mega Drive Play TV 3 (World).*" -Destination ".\Japan\Alternate Releases\"
Move-Item -Path ".\Japan\FZ Senki Axis ~ Final Zone (Japan, USA) (En).*" -Destination ".\Japan\Alternate Releases\"
Move-Item -Path ".\Japan\Legend of Galahad, The ~ Galahad (USA, Europe).*" -Destination ".\Japan\Alternate Releases\"
Move-Item -Path ".\Japan\Michael Jackson's Moonwalker (Japan, USA) (En).*" -Destination ".\Japan\Alternate Releases\"
Move-Item -Path ".\Japan\NHL '94 (USA, Europe) (Re-release).*" -Destination ".\Japan\Alternate Releases\"
Move-Item -Path ".\Japan\NHLPA Hockey 93 (USA, Europe) (EA Sports).*" -Destination ".\Japan\Alternate Releases\"
Move-Item -Path ".\Japan\PGA Tour Golf (USA) (HeartBeat Catalyst).*" -Destination ".\Japan\Alternate Releases\"
Move-Item -Path ".\Japan\Raiden Densetsu ~ Raiden Trad (Japan, USA) (En).*" -Destination ".\Japan\Alternate Releases\"
Move-Item -Path ".\Japan\Senjou no Ookami II ~ Mercs (World).*" -Destination ".\Japan\Alternate Releases\"
Move-Item -Path ".\Japan\Sonic Compilation ~ Sonic Classics (USA, Europe, Korea) (En) (Rev A).*" -Destination ".\Japan\Alternate Releases\"
Move-Item -Path ".\Japan\Tatsujin ~ Truxton (World).*" -Destination ".\Japan\Alternate Releases\"
Move-Item -Path ".\Japan\World Cup Soccer ~ World Championship Soccer (Japan, USA) (En) (Rev B).*" -Destination ".\Japan\Alternate Releases\"

# Previous Revisions - Manual Assignment
Move-Item -Path ".\Japan\Lost Vikings, The (USA) (November, 1993).*" -Destination ".\Japan\Previous Revisions"
Move-Item -Path ".\Japan\Olympic Gold (Japan, USA) (En,Fr,De,Es,It,Nl,Pt,Sv).*" -Destination ".\Japan\Previous Revisions"
Move-Item -Path ".\Japan\PGA Tour Golf (USA, Europe) (PGA07).*" -Destination ".\Japan\Previous Revisions"
Move-Item -Path ".\Japan\Revenge of Shinobi, The (Japan, USA) (En).*" -Destination ".\Japan\Previous Revisions"
Move-Item -Path ".\Japan\Super Monaco GP (Japan, USA) (En,Ja).*" -Destination ".\Japan\Previous Revisions"
Move-Item -Path ".\Japan\Super Monaco GP (USA) (En,Ja).*" -Destination ".\Japan\Previous Revisions"
Move-Item -Path ".\Japan\Tinhead (USA) (Ballistic) (April, 1994).*" -Destination ".\Japan\Previous Revisions"

# Hacked Releases
Move-Item -Path ".\Japan\*(*Hack*)*.*" -Destination ".\Japan\Hacks"

# Aftermarket Releases
Move-Item -Path ".\Japan\*(*Aftermarket*)*.*" -Destination ".\Japan\Aftermarket Releases"
Move-Item -Path ".\Japan\*(*Pirate*)*.*" -Destination ".\Japan\Aftermarket Releases"

# Aftermarket Releases - Manual Assignment
Move-Item -Path ".\Japan\River City Girls Zero*.*" -Destination ".\Japan\Aftermarket Releases"
Move-Item -Path ".\Japan\8-BIT ADV STEINS;GATE*.*" -Destination ".\Japan\Aftermarket Releases"

# Unlicensed Releases
Move-Item -Path ".\Japan\*(*Unl*)*.*" -Destination ".\Japan\Unlicensed Releases"

# Official Releases
Move-Item -Path ".\Japan\*.*" -Destination ".\Japan\Official Releases"

Write-Host "Sorting for Japan Complete."