##################################################################
# North America
##################################################################

#################################
# Standard Moves
#################################

Write-Host "Sorting North American Releases..."

Move-Item -Path ".\North America\*Color hack*.*" -Destination ".\North America\Hacks\Enhanced Colors"
Move-Item -Path ".\North America\*FastROM hack*.*" -Destination ".\North America\Hacks\FastROM"

# Pre-Release
Move-Item -Path ".\North America\*(*Beta*)*.*" -Destination ".\North America\Pre-Release\Beta"
Move-Item -Path ".\North America\*(*Demo*)*.*" -Destination ".\North America\Pre-Release\Demo"
Move-Item -Path ".\North America\*Sampler CD*.*" -Destination ".\North America\Pre-Release\Demo"
Move-Item -Path ".\North America\*Sampler Disc*.*" -Destination ".\North America\Pre-Release\Demo"
Move-Item -Path ".\North America\*Sampler Disk*.*" -Destination ".\North America\Pre-Release\Demo"
Move-Item -Path ".\North America\*CD Sampler*.*" -Destination ".\North America\Pre-Release\Demo"
Move-Item -Path ".\North America\*Demo CD*.*" -Destination ".\North America\Pre-Release\Demo"
Move-Item -Path ".\North America\*Demo Disc*.*" -Destination ".\North America\Pre-Release\Demo"
Move-Item -Path ".\North America\*Demo Disk*.*" -Destination ".\North America\Pre-Release\Demo"
Move-Item -Path ".\North America\Asciiware Training CD*.*" -Destination ".\North America\Pre-Release\Demo"
Move-Item -Path ".\North America\*Squaresoft on PlayStation*.*" -Destination ".\North America\Pre-Release\Demo"
Move-Item -Path ".\North America\*PlayStation Underground*.*" -Destination ".\North America\Pre-Release\Demo"
Move-Item -Path ".\North America\Dreamcast Express*.*" -Destination ".\North America\Pre-Release\Demo"
Move-Item -Path ".\North America\Dreamcast Middleware Conference Demo Disc*.*" -Destination ".\North America\Pre-Release\Demo"
Move-Item -Path ".\North America\Dreamcast Promotion Disk*.*" -Destination ".\North America\Pre-Release\Demo"
Move-Item -Path ".\North America\Dreamon*.*" -Destination ".\North America\Pre-Release\Demo"
Move-Item -Path ".\North America\Generator Vol*.*" -Destination ".\North America\Pre-Release\Demo"
Move-Item -Path ".\North America\Interactive Multi-Game Demo Disc*.*" -Destination ".\North America\Pre-Release\Demo"
Move-Item -Path ".\North America\Interactive Preview Plus*.*" -Destination ".\North America\Pre-Release\Demo"
Move-Item -Path ".\North America\Jampack Vol*.*" -Destination ".\North America\Pre-Release\Demo"
Move-Item -Path ".\North America\Official Sega Dreamcast Magazine*.*" -Destination ".\North America\Pre-Release\Demo"
Move-Item -Path ".\North America\Official U.S. PlayStation Magazine Demo*.*" -Destination ".\North America\Pre-Release\Demo"
Move-Item -Path ".\North America\Pizza Hut Disc*.*" -Destination ".\North America\Pre-Release\Demo"
Move-Item -Path ".\North America\PlayStation Kiosk Demo*.*" -Destination ".\North America\Pre-Release\Demo"
Move-Item -Path ".\North America\PlayStation Picks*.*" -Destination ".\North America\Pre-Release\Demo"
Move-Item -Path ".\North America\PS One*.*" -Destination ".\North America\Pre-Release\Demo"
Move-Item -Path ".\North America\PS-X-Change*.*" -Destination ".\North America\Pre-Release\Demo"
Move-Item -Path ".\North America\PSone*.*" -Destination ".\North America\Pre-Release\Demo"
Move-Item -Path ".\North America\Toys R Us - Attack of the Killer Demos*.*" -Destination ".\North America\Pre-Release\Demo"
Move-Item -Path ".\North America\Toys R Us Test Drive Promotion*.*" -Destination ".\North America\Pre-Release\Demo"
Move-Item -Path ".\North America\*(*Proto*)*.*" -Destination ".\North America\Pre-Release\Prototype"

# Test Cartridges & Utilities
Move-Item -Path ".\North America\*(*Program*)*.*" -Destination ".\North America\Test Cartridges & Utilities"
Move-Item -Path ".\North America\*(*Enhancement*Chip*)*.*" -Destination ".\North America\Test Cartridges & Utilities"
Move-Item -Path ".\North America\*(*Audio*Tapes*)*.*" -Destination ".\North America\Test Cartridges & Utilities"
Move-Item -Path ".\North America\*(*Sample*)*.*" -Destination ".\North America\Pre-Release\Sample"
Move-Item -Path ".\North America\*(*Debug*)*.*" -Destination ".\North America\Test Cartridges & Utilities"
Move-Item -Path ".\North America\*(*Prerelease*)*.*" -Destination ".\North America\Pre-Release"
Move-Item -Path ".\North America\*(*Test*Program*)*.*" -Destination ".\North America\Test Cartridges & Utilities"
Move-Item -Path ".\North America\*Service Disc*.*" -Destination ".\North America\Test Cartridges & Utilities"
Move-Item -Path ".\North America\*(*SDK*Build*)*.*" -Destination ".\North America\Test Cartridges & Utilities"
Move-Item -Path ".\North America\*Action Replay*.*" -Destination ".\North America\Test Cartridges & Utilities"
Move-Item -Path ".\North America\*Super*Game*Boy*.*" -Destination ".\North America\Test Cartridges & Utilities"
Move-Item -Path ".\North America\*Burn-in*Test*.*" -Destination ".\North America\Test Cartridges & Utilities"
Move-Item -Path ".\North America\*Demonstration*Program*.*" -Destination ".\North America\Test Cartridges & Utilities"
Move-Item -Path ".\North America\*Diagnostics*.*" -Destination ".\North America\Test Cartridges & Utilities"
Move-Item -Path ".\North America\*Flash*Masta*Firmware*.*" -Destination ".\North America\Test Cartridges & Utilities"
Move-Item -Path ".\North America\*Game*Genie*.*" -Destination ".\North America\Test Cartridges & Utilities"
Move-Item -Path ".\North America\*Info Genius Productivity Pak*.*" -Destination ".\North America\Test Cartridges & Utilities"
Move-Item -Path ".\North America\Advanced Music Player*.*" -Destination ".\North America\Test Cartridges & Utilities"
Move-Item -Path ".\North America\Aging Disc DOL-*.*" -Destination ".\North America\Test Cartridges & Utilities"
Move-Item -Path ".\North America\Aprilia - DiTech Interface*.*" -Destination ".\North America\Test Cartridges & Utilities"
Move-Item -Path ".\North America\Atari*PAM*.*" -Destination ".\North America\Test Cartridges & Utilities"
Move-Item -Path ".\North America\Breaker Pro*.*" -Destination ".\North America\Test Cartridges & Utilities"
Move-Item -Path ".\North America\Cheats 'N Codes Volume*.*" -Destination ".\North America\Test Cartridges & Utilities"
Move-Item -Path ".\North America\Code Breaker*.*" -Destination ".\North America\Test Cartridges & Utilities"
Move-Item -Path ".\North America\CodeBreaker*.*" -Destination ".\North America\Test Cartridges & Utilities"
Move-Item -Path ".\North America\Codemasters Demo CD*.*" -Destination ".\North America\Test Cartridges & Utilities"
Move-Item -Path ".\North America\Doctor GB Card*.*" -Destination ".\North America\Test Cartridges & Utilities"
Move-Item -Path ".\North America\Dreamkey*.*" -Destination ".\North America\Test Cartridges & Utilities"
Move-Item -Path ".\North America\Game Boy Camera*.*" -Destination ".\North America\Test Cartridges & Utilities"
Move-Item -Path ".\North America\Game Boy Player Start-Up Disc*.*" -Destination ".\North America\Test Cartridges & Utilities"
Move-Item -Path ".\North America\GameBooster 64*.*" -Destination ".\North America\Test Cartridges & Utilities"
Move-Item -Path ".\North America\GameShark*.*" -Destination ".\North America\Test Cartridges & Utilities"
Move-Item -Path ".\North America\GBA Jukebox*.*" -Destination ".\North America\Test Cartridges & Utilities"
Move-Item -Path ".\North America\GBA Personal Organizer*.*" -Destination ".\North America\Test Cartridges & Utilities"
Move-Item -Path ".\North America\JRA PAT for Dreamcast*.*" -Destination ".\North America\Test Cartridges & Utilities"
Move-Item -Path ".\North America\Lynx II Production Test Program (USA)*.*" -Destination ".\North America\Test Cartridges & Utilities"
Move-Item -Path ".\North America\Nintendo 64 Modem*.*" -Destination ".\North America\Test Cartridges & Utilities"
Move-Item -Path ".\North America\Randnet*.*" -Destination ".\North America\Test Cartridges & Utilities"
Move-Item -Path ".\North America\Ultimate Codes for Use with*.*" -Destination ".\North America\Test Cartridges & Utilities"
Move-Item -Path ".\North America\Web Browser*.*" -Destination ".\North America\Test Cartridges & Utilities"
Move-Item -Path ".\North America\XBAND*.*" -Destination ".\North America\Test Cartridges & Utilities"
Move-Item -Path ".\North America\Game Boy Aging Cartridge*.*" -Destination ".\North America\Test Cartridges & Utilities"
Move-Item -Path ".\North America\Atari 7800 Development Card (USA).*" -Destination ".\North America\Test Cartridges & Utilities"
Move-Item -Path ".\North America\Super NES Control Deck Tester (USA)*.*" -Destination ".\North America\Test Cartridges & Utilities"
Move-Item -Path ".\North America\World Class Service Super Nintendo Tester (USA).*" -Destination ".\North America\Test Cartridges & Utilities"

# Alternate Releases
Move-Item -Path ".\North America\*(*Promo*)*.*" -Destination ".\North America\Alternate Releases"
Move-Item -Path ".\North America\*(*Arcade*)*.*" -Destination ".\North America\Alternate Releases"
Move-Item -Path ".\North America\*(*Anthology*)*.*" -Destination ".\North America\Alternate Releases\Collections"
Move-Item -Path ".\North America\*(*Capcom*Classics*Mini*Mix*)*.*" -Destination ".\North America\Alternate Releases\Collections"
Move-Item -Path ".\North America\*(*Collect*)*.*" -Destination ".\North America\Alternate Releases\Collections"
Move-Item -Path ".\North America\*(*Disney*)*.*" -Destination ".\North America\Alternate Releases"
Move-Item -Path ".\North America\*(*e-Reader*)*.*" -Destination ".\North America\Alternate Releases\eReader Edition"
Move-Item -Path ".\North America\*(*Final*Cut*)*.*" -Destination ".\North America\Alternate Releases"
Move-Item -Path ".\North America\*(*GameCube*)*.*" -Destination ".\North America\Alternate Releases\GameCube Edition"
Move-Item -Path ".\North America\*(*Genesis*Mini*)*.*" -Destination ".\North America\Alternate Releases"
Move-Item -Path ".\North America\*(*LodgeNet*)*.*" -Destination ".\North America\Alternate Releases"
Move-Item -Path ".\North America\*(*Namco*Museum*)*.*" -Destination ".\North America\Alternate Releases\Collections"
Move-Item -Path ".\North America\*(*PC*Rerelease*)*.*" -Destination ".\North America\Alternate Releases"
Move-Item -Path ".\North America\*(*Sega*)*.*" -Destination ".\North America\Alternate Releases"
Move-Item -Path ".\North America\*(*Switch*)*.*" -Destination ".\North America\Alternate Releases\Switch Online"
Move-Item -Path ".\North America\*(*Virtual*Console)*.*" -Destination ".\North America\Alternate Releases\Virtual Console"
Move-Item -Path ".\North America\*(*Retro-Bit*)*.*" -Destination ".\North America\Alternate Releases\"
Move-Item -Path ".\North America\*(*iam8bit*)*.*" -Destination ".\North America\Alternate Releases\"
Move-Item -Path ".\North America\*(*Capcom*Town*)*.*" -Destination ".\North America\Alternate Releases\"
Move-Item -Path ".\North America\*(*Limited Run Games*)*.*" -Destination ".\North America\Alternate Releases\"
Move-Item -Path ".\North America\*(*Steam*)*.*" -Destination ".\North America\Alternate Releases\"
Move-Item -Path ".\North America\*(*QUByte Classics*)*.*" -Destination ".\North America\Alternate Releases\"
Move-Item -Path ".\North America\*(*Piko Interactive*)*.*" -Destination ".\North America\Alternate Releases\"
Move-Item -Path ".\North America\*(Strictly Limited Games)*.*" -Destination ".\North America\Alternate Releases\"
Move-Item -Path ".\North America\*(Evercade)*.*" -Destination ".\North America\Alternate Releases\"
Move-Item -Path ".\North America\*(*Wii*)*.*" -Destination ".\North America\Alternate Releases"
Move-Item -Path ".\North America\e-Reader (USA)*.*" -Destination ".\North America\Alternate Releases\eReader Edition"
Move-Item -Path ".\North America\*(Alt)*.*" -Destination ".\North America\Alternate Releases\"
Move-Item -Path ".\North America\*(*Alternate*)*.*" -Destination ".\North America\Alternate Releases\"
Move-Item -Path ".\North America\*(PROPER 12K)*.*" -Destination ".\North America\Alternate Releases\"

# Alternate Releases - Multi-Cart
Move-Item -Path ".\North America\2 Game Pack*.*" -Destination ".\North America\Alternate Releases\Multi-Cart"
Move-Item -Path ".\North America\2 Games in 1*.*" -Destination ".\North America\Alternate Releases\Multi-Cart"
Move-Item -Path ".\North America\2 Games in One*.*" -Destination ".\North America\Alternate Releases\Multi-Cart"
Move-Item -Path ".\North America\2 Great Games*.*" -Destination ".\North America\Alternate Releases\Multi-Cart"
Move-Item -Path ".\North America\2 in 1 Game Pack*.*" -Destination ".\North America\Alternate Releases\Multi-Cart"
Move-Item -Path ".\North America\2-in-1 Fun Pack*.*" -Destination ".\North America\Alternate Releases\Multi-Cart"
Move-Item -Path ".\North America\3 Game Pack*.*" -Destination ".\North America\Alternate Releases\Multi-Cart"
Move-Item -Path ".\North America\3 Games in 1*.*" -Destination ".\North America\Alternate Releases\Multi-Cart"
Move-Item -Path ".\North America\3 Games in One*.*" -Destination ".\North America\Alternate Releases\Multi-Cart"
Move-Item -Path ".\North America\4 Games on One Game Pak*.*" -Destination ".\North America\Alternate Releases\Multi-Cart"
Move-Item -Path ".\North America\4 in 1 + 8 in 1*.*" -Destination ".\North America\Alternate Releases\Multi-Cart"

# Alternate Releases - Manual Assignment
Move-Item -Path ".\North America\Blitz! - Action Football (USA, Europe) (0F11CE0C).*" -Destination ".\North America\Alternate Releases\"
Move-Item -Path ".\North America\Blitz! - Action Football (USA, Europe) (881B27C5).*" -Destination ".\North America\Alternate Releases\"
Move-Item -Path ".\North America\Pole Position (USA) (A00ED3D6).*" -Destination ".\North America\Alternate Releases\"
Move-Item -Path ".\North America\Pole Position (USA) (C10F37D8).*" -Destination ".\North America\Alternate Releases\"
Move-Item -Path ".\North America\*[*Un-Worked Design by Supper*]*.*" -Destination ".\North America\Alternate Releases\"
Move-Item -Path ".\North America\Tecmo NBA Basketball (USA) (NES-N7).*" -Destination ".\North America\Alternate Releases\"
Move-Item -Path ".\North America\Tecmo Super NBA Basketball (USA) (SNS-NA).*" -Destination ".\North America\Alternate Releases\"
Move-Item -Path ".\North America\Wild Gunman (Japan, USA) (En).*" -Destination ".\North America\Alternate Releases\"
Move-Item -Path ".\North America\Kirby's Adventure (Canada) (Fr).*" -Destination ".\North America\Alternate Releases\"
Move-Item -Path ".\North America\Legend of Zelda, The - A Link to the Past (Canada) (Fr).*" -Destination ".\North America\Alternate Releases\"
Move-Item -Path ".\North America\Alex Kidd in Miracle World (USA, Europe, Brazil) (En) (Rev 1).*" -Destination ".\North America\Alternate Releases\"
Move-Item -Path ".\North America\Altered Beast (Japan, USA) (En) (Rev A).*" -Destination ".\North America\Alternate Releases\"
Move-Item -Path ".\North America\Arcade Legends Sega Mega Drive (World).*" -Destination ".\North America\Alternate Releases\"
Move-Item -Path ".\North America\Arcade Legends Sega Mega Drive ~ Arcade Legends Sega Genesis ~ Mega Drive Play TV (World).*" -Destination ".\North America\Alternate Releases\"
Move-Item -Path ".\North America\Arcade Legends Street Fighter II' - Special Champion Edition (World).*" -Destination ".\North America\Alternate Releases\"
Move-Item -Path ".\North America\Arcade Legends Street Fighter II' - Special Champion Edition ~ Mega Drive Play TV 3 (World).*" -Destination ".\North America\Alternate Releases\"
Move-Item -Path ".\North America\FZ Senki Axis ~ Final Zone (Japan, USA) (En).*" -Destination ".\North America\Alternate Releases\"
Move-Item -Path ".\North America\Legend of Galahad, The ~ Galahad (USA, Europe).*" -Destination ".\North America\Alternate Releases\"
Move-Item -Path ".\North America\Michael Jackson's Moonwalker (Japan, USA) (En).*" -Destination ".\North America\Alternate Releases\"
Move-Item -Path ".\North America\NHL '94 (USA, Europe) (Re-release).*" -Destination ".\North America\Alternate Releases\"
Move-Item -Path ".\North America\NHLPA Hockey 93 (USA, Europe) (EA Sports).*" -Destination ".\North America\Alternate Releases\"
Move-Item -Path ".\North America\PGA Tour Golf (USA) (HeartBeat Catalyst).*" -Destination ".\North America\Alternate Releases\"
Move-Item -Path ".\North America\Raiden Densetsu ~ Raiden Trad (Japan, USA) (En).*" -Destination ".\North America\Alternate Releases\"
Move-Item -Path ".\North America\Senjou no Ookami II ~ Mercs (World).*" -Destination ".\North America\Alternate Releases\"
Move-Item -Path ".\North America\Sonic Compilation ~ Sonic Classics (USA, Europe, Korea) (En) (Rev A).*" -Destination ".\North America\Alternate Releases\"
Move-Item -Path ".\North America\Tatsujin ~ Truxton (World).*" -Destination ".\North America\Alternate Releases\"
Move-Item -Path ".\North America\World Cup Soccer ~ World Championship Soccer (Japan, USA) (En) (Rev B).*" -Destination ".\North America\Alternate Releases\"

# Previous Revisions - Manual Assignment
Move-Item -Path ".\North America\Lost Vikings, The (USA) (November, 1993).*" -Destination ".\North America\Previous Revisions"
Move-Item -Path ".\North America\Olympic Gold (Japan, USA) (En,Fr,De,Es,It,Nl,Pt,Sv).*" -Destination ".\North America\Previous Revisions"
Move-Item -Path ".\North America\PGA Tour Golf (USA, Europe) (PGA07).*" -Destination ".\North America\Previous Revisions"
Move-Item -Path ".\North America\Revenge of Shinobi, The (Japan, USA) (En).*" -Destination ".\North America\Previous Revisions"
Move-Item -Path ".\North America\Super Monaco GP (Japan, USA) (En,Ja).*" -Destination ".\North America\Previous Revisions"
Move-Item -Path ".\North America\Super Monaco GP (USA) (En,Ja).*" -Destination ".\North America\Previous Revisions"
Move-Item -Path ".\North America\Tinhead (USA) (Ballistic) (April, 1994).*" -Destination ".\North America\Previous Revisions"

# Hacked Releases
Move-Item -Path ".\North America\*(*Hack*)*.*" -Destination ".\North America\Hacks"

# Aftermarket Releases
Move-Item -Path ".\North America\*(*Aftermarket*)*.*" -Destination ".\North America\Aftermarket Releases"
Move-Item -Path ".\North America\*(*Pirate*)*.*" -Destination ".\North America\Aftermarket Releases"

# Aftermarket Releases - Manual Assignment
Move-Item -Path ".\North America\River City Girls Zero*.*" -Destination ".\North America\Aftermarket Releases"
Move-Item -Path ".\North America\8-BIT ADV STEINS;GATE*.*" -Destination ".\North America\Aftermarket Releases"

# Unlicensed Releases
Move-Item -Path ".\North America\*(*Unl*)*.*" -Destination ".\North America\Unlicensed Releases"

# Official Releases
Move-Item -Path ".\North America\*.*" -Destination ".\North America\Official Releases"

Write-Host "Sorting for North America Complete."
