##################################################################
# Minor Regions (Other)
##################################################################

#################################
# Standard Moves
#################################

Write-Host "Sorting Minor Region Releases..."

Move-Item -Path ".\Other\*Color hack*.*" -Destination ".\Other\Hacks\Enhanced Colors"
Move-Item -Path ".\Other\*FastROM hack*.*" -Destination ".\Other\Hacks\FastROM"

# Pre-Release
Move-Item -Path ".\Other\*(*Beta*)*.*" -Destination ".\Other\Pre-Release\Beta"
Move-Item -Path ".\Other\*(*Demo*)*.*" -Destination ".\Other\Pre-Release\Demo"
Move-Item -Path ".\Other\*Sampler CD*.*" -Destination ".\Other\Pre-Release\Demo"
Move-Item -Path ".\Other\*Sampler Disc*.*" -Destination ".\Other\Pre-Release\Demo"
Move-Item -Path ".\Other\*Sampler Disk*.*" -Destination ".\Other\Pre-Release\Demo"
Move-Item -Path ".\Other\*CD Sampler*.*" -Destination ".\Other\Pre-Release\Demo"
Move-Item -Path ".\Other\*Demo CD*.*" -Destination ".\Other\Pre-Release\Demo"
Move-Item -Path ".\Other\*Demo Disc*.*" -Destination ".\Other\Pre-Release\Demo"
Move-Item -Path ".\Other\*Demo Disk*.*" -Destination ".\Other\Pre-Release\Demo"
Move-Item -Path ".\Other\Asciiware Training CD*.*" -Destination ".\Other\Pre-Release\Demo"
Move-Item -Path ".\Other\*Squaresoft on PlayStation*.*" -Destination ".\Other\Pre-Release\Demo"
Move-Item -Path ".\Other\*PlayStation Underground*.*" -Destination ".\Other\Pre-Release\Demo"
Move-Item -Path ".\Other\Dreamcast Express*.*" -Destination ".\Other\Pre-Release\Demo"
Move-Item -Path ".\Other\Dreamcast Middleware Conference Demo Disc*.*" -Destination ".\Other\Pre-Release\Demo"
Move-Item -Path ".\Other\Dreamcast Promotion Disk*.*" -Destination ".\Other\Pre-Release\Demo"
Move-Item -Path ".\Other\Dreamon*.*" -Destination ".\Other\Pre-Release\Demo"
Move-Item -Path ".\Other\Generator Vol*.*" -Destination ".\Other\Pre-Release\Demo"
Move-Item -Path ".\Other\Interactive Multi-Game Demo Disc*.*" -Destination ".\Other\Pre-Release\Demo"
Move-Item -Path ".\Other\Interactive Preview Plus*.*" -Destination ".\Other\Pre-Release\Demo"
Move-Item -Path ".\Other\Jampack Vol*.*" -Destination ".\Other\Pre-Release\Demo"
Move-Item -Path ".\Other\Official Sega Dreamcast Magazine*.*" -Destination ".\Other\Pre-Release\Demo"
Move-Item -Path ".\Other\Official U.S. PlayStation Magazine Demo*.*" -Destination ".\Other\Pre-Release\Demo"
Move-Item -Path ".\Other\Pizza Hut Disc*.*" -Destination ".\Other\Pre-Release\Demo"
Move-Item -Path ".\Other\PlayStation Kiosk Demo*.*" -Destination ".\Other\Pre-Release\Demo"
Move-Item -Path ".\Other\PlayStation Picks*.*" -Destination ".\Other\Pre-Release\Demo"
Move-Item -Path ".\Other\PS One*.*" -Destination ".\Other\Pre-Release\Demo"
Move-Item -Path ".\Other\PS-X-Change*.*" -Destination ".\Other\Pre-Release\Demo"
Move-Item -Path ".\Other\PSone*.*" -Destination ".\Other\Pre-Release\Demo"
Move-Item -Path ".\Other\Toys R Us - Attack of the Killer Demos*.*" -Destination ".\Other\Pre-Release\Demo"
Move-Item -Path ".\Other\Toys R Us Test Drive Promotion*.*" -Destination ".\Other\Pre-Release\Demo"
Move-Item -Path ".\Other\*(*Proto*)*.*" -Destination ".\Other\Pre-Release\Prototype"

# Test Cartridges & Utilities
Move-Item -Path ".\Other\*(*Program*)*.*" -Destination ".\Other\Test Cartridges & Utilities"
Move-Item -Path ".\Other\*(*Enhancement*Chip*)*.*" -Destination ".\Other\Test Cartridges & Utilities"
Move-Item -Path ".\Other\*(*Audio*Tapes*)*.*" -Destination ".\Other\Test Cartridges & Utilities"
Move-Item -Path ".\Other\*(*Sample*)*.*" -Destination ".\Other\Pre-Release\Sample"
Move-Item -Path ".\Other\*(*Debug*)*.*" -Destination ".\Other\Test Cartridges & Utilities"
Move-Item -Path ".\Other\*(*Prerelease*)*.*" -Destination ".\Other\Pre-Release"
Move-Item -Path ".\Other\*(*Test*Program*)*.*" -Destination ".\Other\Test Cartridges & Utilities"
Move-Item -Path ".\Other\*Service Disc*.*" -Destination ".\Other\Test Cartridges & Utilities"
Move-Item -Path ".\Other\*(*SDK*Build*)*.*" -Destination ".\Other\Test Cartridges & Utilities"
Move-Item -Path ".\Other\*Action Replay*.*" -Destination ".\Other\Test Cartridges & Utilities"
Move-Item -Path ".\Other\*Super*Game*Boy*.*" -Destination ".\Other\Test Cartridges & Utilities"
Move-Item -Path ".\Other\*Burn-in*Test*.*" -Destination ".\Other\Test Cartridges & Utilities"
Move-Item -Path ".\Other\*Demonstration*Program*.*" -Destination ".\Other\Test Cartridges & Utilities"
Move-Item -Path ".\Other\*Diagnostics*.*" -Destination ".\Other\Test Cartridges & Utilities"
Move-Item -Path ".\Other\*Flash*Masta*Firmware*.*" -Destination ".\Other\Test Cartridges & Utilities"
Move-Item -Path ".\Other\*Game*Genie*.*" -Destination ".\Other\Test Cartridges & Utilities"
Move-Item -Path ".\Other\*Info Genius Productivity Pak*.*" -Destination ".\Other\Test Cartridges & Utilities"
Move-Item -Path ".\Other\Advanced Music Player*.*" -Destination ".\Other\Test Cartridges & Utilities"
Move-Item -Path ".\Other\Aging Disc DOL-*.*" -Destination ".\Other\Test Cartridges & Utilities"
Move-Item -Path ".\Other\Aprilia - DiTech Interface*.*" -Destination ".\Other\Test Cartridges & Utilities"
Move-Item -Path ".\Other\Atari*PAM*.*" -Destination ".\Other\Test Cartridges & Utilities"
Move-Item -Path ".\Other\Breaker Pro*.*" -Destination ".\Other\Test Cartridges & Utilities"
Move-Item -Path ".\Other\Cheats 'N Codes Volume*.*" -Destination ".\Other\Test Cartridges & Utilities"
Move-Item -Path ".\Other\Code Breaker*.*" -Destination ".\Other\Test Cartridges & Utilities"
Move-Item -Path ".\Other\CodeBreaker*.*" -Destination ".\Other\Test Cartridges & Utilities"
Move-Item -Path ".\Other\Codemasters Demo CD*.*" -Destination ".\Other\Test Cartridges & Utilities"
Move-Item -Path ".\Other\Doctor GB Card*.*" -Destination ".\Other\Test Cartridges & Utilities"
Move-Item -Path ".\Other\Dreamkey*.*" -Destination ".\Other\Test Cartridges & Utilities"
Move-Item -Path ".\Other\Game Boy Camera*.*" -Destination ".\Other\Test Cartridges & Utilities"
Move-Item -Path ".\Other\Game Boy Player Start-Up Disc*.*" -Destination ".\Other\Test Cartridges & Utilities"
Move-Item -Path ".\Other\GameBooster 64*.*" -Destination ".\Other\Test Cartridges & Utilities"
Move-Item -Path ".\Other\GameShark*.*" -Destination ".\Other\Test Cartridges & Utilities"
Move-Item -Path ".\Other\GBA Jukebox*.*" -Destination ".\Other\Test Cartridges & Utilities"
Move-Item -Path ".\Other\GBA Personal Organizer*.*" -Destination ".\Other\Test Cartridges & Utilities"
Move-Item -Path ".\Other\JRA PAT for Dreamcast*.*" -Destination ".\Other\Test Cartridges & Utilities"
Move-Item -Path ".\Other\Lynx II Production Test Program (USA)*.*" -Destination ".\Other\Test Cartridges & Utilities"
Move-Item -Path ".\Other\Nintendo 64 Modem*.*" -Destination ".\Other\Test Cartridges & Utilities"
Move-Item -Path ".\Other\Randnet*.*" -Destination ".\Other\Test Cartridges & Utilities"
Move-Item -Path ".\Other\Ultimate Codes for Use with*.*" -Destination ".\Other\Test Cartridges & Utilities"
Move-Item -Path ".\Other\Web Browser*.*" -Destination ".\Other\Test Cartridges & Utilities"
Move-Item -Path ".\Other\XBAND*.*" -Destination ".\Other\Test Cartridges & Utilities"
Move-Item -Path ".\Other\Game Boy Aging Cartridge*.*" -Destination ".\Other\Test Cartridges & Utilities"
Move-Item -Path ".\Other\Atari 7800 Development Card (USA).*" -Destination ".\Other\Test Cartridges & Utilities"
Move-Item -Path ".\Other\Super NES Control Deck Tester (USA)*.*" -Destination ".\Other\Test Cartridges & Utilities"
Move-Item -Path ".\Other\World Class Service Super Nintendo Tester (USA).*" -Destination ".\Other\Test Cartridges & Utilities"

# Alternate Releases
Move-Item -Path ".\Other\*(*Promo*)*.*" -Destination ".\Other\Alternate Releases"
Move-Item -Path ".\Other\*(*Arcade*)*.*" -Destination ".\Other\Alternate Releases"
Move-Item -Path ".\Other\*(*Anthology*)*.*" -Destination ".\Other\Alternate Releases\Collections"
Move-Item -Path ".\Other\*(*Capcom*Classics*Mini*Mix*)*.*" -Destination ".\Other\Alternate Releases\Collections"
Move-Item -Path ".\Other\*(*Collect*)*.*" -Destination ".\Other\Alternate Releases\Collections"
Move-Item -Path ".\Other\*(*Disney*)*.*" -Destination ".\Other\Alternate Releases"
Move-Item -Path ".\Other\*(*e-Reader*)*.*" -Destination ".\Other\Alternate Releases\eReader Edition"
Move-Item -Path ".\Other\*(*Final*Cut*)*.*" -Destination ".\Other\Alternate Releases"
Move-Item -Path ".\Other\*(*GameCube*)*.*" -Destination ".\Other\Alternate Releases\GameCube Edition"
Move-Item -Path ".\Other\*(*Genesis*Mini*)*.*" -Destination ".\Other\Alternate Releases"
Move-Item -Path ".\Other\*(*LodgeNet*)*.*" -Destination ".\Other\Alternate Releases"
Move-Item -Path ".\Other\*(*Namco*Museum*)*.*" -Destination ".\Other\Alternate Releases\Collections"
Move-Item -Path ".\Other\*(*PC*Rerelease*)*.*" -Destination ".\Other\Alternate Releases"
Move-Item -Path ".\Other\*(*Sega*)*.*" -Destination ".\Other\Alternate Releases"
Move-Item -Path ".\Other\*(*Switch*)*.*" -Destination ".\Other\Alternate Releases\Switch Online"
Move-Item -Path ".\Other\*(*Virtual*Console)*.*" -Destination ".\Other\Alternate Releases\Virtual Console"
Move-Item -Path ".\Other\*(*Retro-Bit*)*.*" -Destination ".\Other\Alternate Releases\"
Move-Item -Path ".\Other\*(*iam8bit*)*.*" -Destination ".\Other\Alternate Releases\"
Move-Item -Path ".\Other\*(*Capcom*Town*)*.*" -Destination ".\Other\Alternate Releases\"
Move-Item -Path ".\Other\*(*Limited Run Games*)*.*" -Destination ".\Other\Alternate Releases\"
Move-Item -Path ".\Other\*(*Steam*)*.*" -Destination ".\Other\Alternate Releases\"
Move-Item -Path ".\Other\*(*QUByte Classics*)*.*" -Destination ".\Other\Alternate Releases\"
Move-Item -Path ".\Other\*(*Piko Interactive*)*.*" -Destination ".\Other\Alternate Releases\"
Move-Item -Path ".\Other\*(Strictly Limited Games)*.*" -Destination ".\Other\Alternate Releases\"
Move-Item -Path ".\Other\*(Evercade)*.*" -Destination ".\Other\Alternate Releases\"
Move-Item -Path ".\Other\*(*Wii*)*.*" -Destination ".\Other\Alternate Releases"
Move-Item -Path ".\Other\e-Reader (USA)*.*" -Destination ".\Other\Alternate Releases\eReader Edition"
Move-Item -Path ".\Other\*(Alt)*.*" -Destination ".\Other\Alternate Releases\"
Move-Item -Path ".\Other\*(*Alternate*)*.*" -Destination ".\Other\Alternate Releases\"
Move-Item -Path ".\Other\*(PROPER 12K)*.*" -Destination ".\Other\Alternate Releases\"

# Alternate Releases - Multi-Cart
Move-Item -Path ".\Other\2 Game Pack*.*" -Destination ".\Other\Alternate Releases\Multi-Cart"
Move-Item -Path ".\Other\2 Games in 1*.*" -Destination ".\Other\Alternate Releases\Multi-Cart"
Move-Item -Path ".\Other\2 Games in One*.*" -Destination ".\Other\Alternate Releases\Multi-Cart"
Move-Item -Path ".\Other\2 Great Games*.*" -Destination ".\Other\Alternate Releases\Multi-Cart"
Move-Item -Path ".\Other\2 in 1 Game Pack*.*" -Destination ".\Other\Alternate Releases\Multi-Cart"
Move-Item -Path ".\Other\2-in-1 Fun Pack*.*" -Destination ".\Other\Alternate Releases\Multi-Cart"
Move-Item -Path ".\Other\3 Game Pack*.*" -Destination ".\Other\Alternate Releases\Multi-Cart"
Move-Item -Path ".\Other\3 Games in 1*.*" -Destination ".\Other\Alternate Releases\Multi-Cart"
Move-Item -Path ".\Other\3 Games in One*.*" -Destination ".\Other\Alternate Releases\Multi-Cart"
Move-Item -Path ".\Other\4 Games on One Game Pak*.*" -Destination ".\Other\Alternate Releases\Multi-Cart"
Move-Item -Path ".\Other\4 in 1 + 8 in 1*.*" -Destination ".\Other\Alternate Releases\Multi-Cart"

# Alternate Releases - Manual Assignment
Move-Item -Path ".\Other\Blitz! - Action Football (USA, Europe) (0F11CE0C).*" -Destination ".\Other\Alternate Releases\"
Move-Item -Path ".\Other\Blitz! - Action Football (USA, Europe) (881B27C5).*" -Destination ".\Other\Alternate Releases\"
Move-Item -Path ".\Other\Pole Position (USA) (A00ED3D6).*" -Destination ".\Other\Alternate Releases\"
Move-Item -Path ".\Other\Pole Position (USA) (C10F37D8).*" -Destination ".\Other\Alternate Releases\"
Move-Item -Path ".\Other\*[*Un-Worked Design by Supper*]*.*" -Destination ".\Other\Alternate Releases\"
Move-Item -Path ".\Other\Tecmo NBA Basketball (USA) (NES-N7).*" -Destination ".\Other\Alternate Releases\"
Move-Item -Path ".\Other\Tecmo Super NBA Basketball (USA) (SNS-NA).*" -Destination ".\Other\Alternate Releases\"
Move-Item -Path ".\Other\Wild Gunman (Japan, USA) (En).*" -Destination ".\Other\Alternate Releases\"
Move-Item -Path ".\Other\Kirby's Adventure (Canada) (Fr).*" -Destination ".\Other\Alternate Releases\"
Move-Item -Path ".\Other\Legend of Zelda, The - A Link to the Past (Canada) (Fr).*" -Destination ".\Other\Alternate Releases\"
Move-Item -Path ".\Other\Alex Kidd in Miracle World (USA, Europe, Brazil) (En) (Rev 1).*" -Destination ".\Other\Alternate Releases\"
Move-Item -Path ".\Other\Altered Beast (Japan, USA) (En) (Rev A).*" -Destination ".\Other\Alternate Releases\"
Move-Item -Path ".\Other\Arcade Legends Sega Mega Drive (World).*" -Destination ".\Other\Alternate Releases\"
Move-Item -Path ".\Other\Arcade Legends Sega Mega Drive ~ Arcade Legends Sega Genesis ~ Mega Drive Play TV (World).*" -Destination ".\Other\Alternate Releases\"
Move-Item -Path ".\Other\Arcade Legends Street Fighter II' - Special Champion Edition (World).*" -Destination ".\Other\Alternate Releases\"
Move-Item -Path ".\Other\Arcade Legends Street Fighter II' - Special Champion Edition ~ Mega Drive Play TV 3 (World).*" -Destination ".\Other\Alternate Releases\"
Move-Item -Path ".\Other\FZ Senki Axis ~ Final Zone (Japan, USA) (En).*" -Destination ".\Other\Alternate Releases\"
Move-Item -Path ".\Other\Legend of Galahad, The ~ Galahad (USA, Europe).*" -Destination ".\Other\Alternate Releases\"
Move-Item -Path ".\Other\Michael Jackson's Moonwalker (Japan, USA) (En).*" -Destination ".\Other\Alternate Releases\"
Move-Item -Path ".\Other\NHL '94 (USA, Europe) (Re-release).*" -Destination ".\Other\Alternate Releases\"
Move-Item -Path ".\Other\NHLPA Hockey 93 (USA, Europe) (EA Sports).*" -Destination ".\Other\Alternate Releases\"
Move-Item -Path ".\Other\PGA Tour Golf (USA) (HeartBeat Catalyst).*" -Destination ".\Other\Alternate Releases\"
Move-Item -Path ".\Other\Raiden Densetsu ~ Raiden Trad (Japan, USA) (En).*" -Destination ".\Other\Alternate Releases\"
Move-Item -Path ".\Other\Senjou no Ookami II ~ Mercs (World).*" -Destination ".\Other\Alternate Releases\"
Move-Item -Path ".\Other\Sonic Compilation ~ Sonic Classics (USA, Europe, Korea) (En) (Rev A).*" -Destination ".\Other\Alternate Releases\"
Move-Item -Path ".\Other\Tatsujin ~ Truxton (World).*" -Destination ".\Other\Alternate Releases\"
Move-Item -Path ".\Other\World Cup Soccer ~ World Championship Soccer (Japan, USA) (En) (Rev B).*" -Destination ".\Other\Alternate Releases\"

# Previous Revisions - Manual Assignment
Move-Item -Path ".\Other\Lost Vikings, The (USA) (November, 1993).*" -Destination ".\Other\Previous Revisions"
Move-Item -Path ".\Other\Olympic Gold (Japan, USA) (En,Fr,De,Es,It,Nl,Pt,Sv).*" -Destination ".\Other\Previous Revisions"
Move-Item -Path ".\Other\PGA Tour Golf (USA, Europe) (PGA07).*" -Destination ".\Other\Previous Revisions"
Move-Item -Path ".\Other\Revenge of Shinobi, The (Japan, USA) (En).*" -Destination ".\Other\Previous Revisions"
Move-Item -Path ".\Other\Super Monaco GP (Japan, USA) (En,Ja).*" -Destination ".\Other\Previous Revisions"
Move-Item -Path ".\Other\Super Monaco GP (USA) (En,Ja).*" -Destination ".\Other\Previous Revisions"
Move-Item -Path ".\Other\Tinhead (USA) (Ballistic) (April, 1994).*" -Destination ".\Other\Previous Revisions"

# Hacked Releases
Move-Item -Path ".\Other\*(*Hack*)*.*" -Destination ".\Other\Hacks"

# Aftermarket Releases
Move-Item -Path ".\Other\*(*Aftermarket*)*.*" -Destination ".\Other\Aftermarket Releases"
Move-Item -Path ".\Other\*(*Pirate*)*.*" -Destination ".\Other\Aftermarket Releases"

# Aftermarket Releases - Manual Assignment
Move-Item -Path ".\Other\River City Girls Zero*.*" -Destination ".\Other\Aftermarket Releases"
Move-Item -Path ".\Other\8-BIT ADV STEINS;GATE*.*" -Destination ".\Other\Aftermarket Releases"

# Unlicensed Releases
Move-Item -Path ".\Other\*(*Unl*)*.*" -Destination ".\Other\Unlicensed Releases"

# Official Releases
Move-Item -Path ".\Other\*.*" -Destination ".\Other\Official Releases"

Write-Host "Sorting for Minor Release (Other) Regions Complete."